// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: Valmar_Screen

#ifndef _VALMAR_SCREEN_UI_H
#define _VALMAR_SCREEN_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

///////////////////// SCREENS ////////////////////
#include "ui_splashScreen.h"
#include "ui_runScreen.h"
#include "ui_calibrationScreen.h"
#include "ui_settingsScreen.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_valmar_valmar_png);   // assets/Valmar/valmar.png
LV_IMG_DECLARE( ui_img_valmar_cal_png);   // assets/Valmar/cal.png
LV_IMG_DECLARE( ui_img_639977379);   // assets/Valmar/icons8-satellite-25.png
LV_IMG_DECLARE( ui_img_232107149);   // assets/Valmar/icons8-clock-20.png
LV_IMG_DECLARE( ui_img_1811295523);   // assets/Valmar/icons8-settings-50.png
LV_IMG_DECLARE( ui_img_valmar_back_png);   // assets/Valmar/back.png
LV_IMG_DECLARE( ui_img_1608339404);   // assets/Valmar/icons8-alert-100.png

// FONTS
LV_FONT_DECLARE( ui_font_ConsolaMono);
LV_FONT_DECLARE( ui_font_VeraMono);
LV_FONT_DECLARE( ui_font_ConsolaMono30);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
