// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: Valmar_Screen

#ifndef UI_CALIBRATIONSCREEN2_H
#define UI_CALIBRATIONSCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_calibrationScreen2
extern void ui_calibrationScreen2_screen_init(void);
extern void ui_calibrationScreen2_screen_destroy(void);
extern lv_obj_t *ui_calibrationScreen2;
extern lv_obj_t *ui_Label9;
extern void ui_event_btnCalibrate5( lv_event_t * e);
extern lv_obj_t *ui_btnCalibrate5;
extern void ui_event_btnPage( lv_event_t * e);
extern lv_obj_t *ui_btnPage;
extern void ui_event_Keyboard3( lv_event_t * e);
extern lv_obj_t *ui_Keyboard3;
extern void ui_event_txtSeedPerRev( lv_event_t * e);
extern lv_obj_t *ui_txtSeedPerRev;
extern void ui_event_btnUnlock( lv_event_t * e);
extern lv_obj_t *ui_btnUnlock;
extern void ui_event_btnLock( lv_event_t * e);
extern lv_obj_t *ui_btnLock;
// CUSTOM VARIABLES
extern lv_obj_t *uic_calibrationScreen2;
extern lv_obj_t *uic_btnPage;
extern lv_obj_t *uic_txtSeedPerRev;
extern lv_obj_t *uic_btnLock;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

