// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: Valmar_Screen

#ifndef UI_CALIBRATIONSCREEN1_H
#define UI_CALIBRATIONSCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_calibrationScreen1
extern void ui_calibrationScreen1_screen_init(void);
extern void ui_calibrationScreen1_screen_destroy(void);
extern lv_obj_t *ui_calibrationScreen1;
extern lv_obj_t *ui_Label26;
extern void ui_event_btnPage2( lv_event_t * e);
extern lv_obj_t *ui_btnPage2;
extern void ui_event_Keyboard1( lv_event_t * e);
extern lv_obj_t *ui_Keyboard1;
extern void ui_event_btnCalibrate2( lv_event_t * e);
extern lv_obj_t *ui_btnCalibrate2;
extern lv_obj_t *ui_txtCalWeight;
extern void ui_event_swCalibrate( lv_event_t * e);
extern lv_obj_t *ui_swCalibrate;
// CUSTOM VARIABLES
extern lv_obj_t *uic_calibrationScreen1;
extern lv_obj_t *uic_btnPage2;
extern lv_obj_t *uic_txtCalWeight;
extern lv_obj_t *uic_swCalibrate;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

