// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: Valmar_Screen

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void rateChange(lv_event_t * e);
void warningAcknowledge(lv_event_t * e);
void stopAcknowlege(lv_event_t * e);
void calibrationInput(lv_event_t * e);
void calSwitchToggle(lv_event_t * e);
void backlightControl(lv_event_t * e);
void motorTestUpdatePWM(lv_event_t * e);
void motorTest(lv_event_t * e);
void speedTestUpdateSpeed(lv_event_t * e);
void speedTest(lv_event_t * e);
void initReset(lv_event_t * e);
void seedPerRevManualSet(lv_event_t * e);
void pairController(lv_event_t * e);
void screenFirmware(lv_event_t * e);
void controllerFirmware(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
