// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: Valmar_Screen

#ifndef UI_INFOSCREEN_H
#define UI_INFOSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_infoScreen
extern void ui_infoScreen_screen_init(void);
extern void ui_infoScreen_screen_destroy(void);
extern lv_obj_t *ui_infoScreen;
extern void ui_event_btnCalibrate4( lv_event_t * e);
extern lv_obj_t *ui_btnCalibrate4;
extern lv_obj_t *ui_Label17;
extern lv_obj_t *ui_Label18;
// CUSTOM VARIABLES
extern lv_obj_t *uic_infoScreen;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

