// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: Valmar_Screen

#ifndef UI_RUNSCREEN_H
#define UI_RUNSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_runScreen
extern void ui_runScreen_screen_init(void);
extern void ui_runScreen_screen_destroy(void);
extern void ui_event_runScreen( lv_event_t * e);
extern lv_obj_t *ui_runScreen;
extern lv_obj_t *ui_Container1;
extern lv_obj_t *ui_lblTime;
extern lv_obj_t *ui_containerRate;
extern void ui_event_spinboxRate( lv_event_t * e);
extern lv_obj_t *ui_spinboxRate;
extern void ui_event_btnPlus( lv_event_t * e);
extern lv_obj_t *ui_btnPlus;
extern lv_obj_t *ui_Container2;
extern lv_obj_t *ui_Label3;
extern void ui_event_btnMinus( lv_event_t * e);
extern lv_obj_t *ui_btnMinus;
extern lv_obj_t *ui_Container3;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Label5;
extern void ui_event_btnCalibrate( lv_event_t * e);
extern lv_obj_t *ui_btnCalibrate;
extern void ui_event_btnSettings( lv_event_t * e);
extern lv_obj_t *ui_btnSettings;
extern void ui_event_btnInfo( lv_event_t * e);
extern lv_obj_t *ui_btnInfo;
extern lv_obj_t *ui_imgGPSFix;
extern lv_obj_t *ui_lblNumSats;
extern lv_obj_t *ui_Image4;
extern lv_obj_t *ui_Container4;
extern lv_obj_t *ui_Container5;
extern lv_obj_t *ui_Container6;
extern lv_obj_t *ui_Container7;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_lblSpeed;
extern lv_obj_t *ui_lblShaftRPM;
extern lv_obj_t *ui_lblRate;
extern lv_obj_t *ui_Container8;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_workLED;
// CUSTOM VARIABLES
extern lv_obj_t *uic_runScreen;
extern lv_obj_t *uic_lblTime;
extern lv_obj_t *uic_spinboxRate;
extern lv_obj_t *uic_btnCalibrate;
extern lv_obj_t *uic_btnSettings;
extern lv_obj_t *uic_btnInfo;
extern lv_obj_t *uic_imgGPSFix;
extern lv_obj_t *uic_lblNumSats;
extern lv_obj_t *uic_lblSpeed;
extern lv_obj_t *uic_lblShaftRPM;
extern lv_obj_t *uic_lblRate;
extern lv_obj_t *uic_workLED;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

