// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: Valmar_Screen

#ifndef UI_SETTINGSSCREEN2_H
#define UI_SETTINGSSCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_settingsScreen2
extern void ui_settingsScreen2_screen_init(void);
extern void ui_settingsScreen2_screen_destroy(void);
extern lv_obj_t *ui_settingsScreen2;
extern void ui_event_btnPage3( lv_event_t * e);
extern lv_obj_t *ui_btnPage3;
extern void ui_event_sldBrightness( lv_event_t * e);
extern lv_obj_t *ui_sldBrightness;
extern lv_obj_t *ui_Label25;
extern void ui_event_btnBack1( lv_event_t * e);
extern lv_obj_t *ui_btnBack1;
extern void ui_event_arcMotorPWM( lv_event_t * e);
extern lv_obj_t *ui_arcMotorPWM;
extern lv_obj_t *ui_Label14;
extern void ui_event_swMotorTest( lv_event_t * e);
extern lv_obj_t *ui_swMotorTest;
extern lv_obj_t *ui_lblPWM;
extern lv_obj_t *ui_lblRPM;
extern lv_obj_t *ui_Label15;
extern lv_obj_t *ui_Label16;
extern void ui_event_arcTestSpeed( lv_event_t * e);
extern lv_obj_t *ui_arcTestSpeed;
extern lv_obj_t *ui_Label19;
extern void ui_event_swSpeedTest( lv_event_t * e);
extern lv_obj_t *ui_swSpeedTest;
extern lv_obj_t *ui_lblTestSpeed;
extern lv_obj_t *ui_Label21;
extern lv_obj_t *ui_panelReset;
extern lv_obj_t *ui_Label12;
extern lv_obj_t *ui_Image5;
extern void ui_event_btnResetYes( lv_event_t * e);
extern lv_obj_t *ui_btnResetYes;
extern lv_obj_t *ui_Label13;
extern void ui_event_btnResetNo( lv_event_t * e);
extern lv_obj_t *ui_btnResetNo;
extern lv_obj_t *ui_Label2;
extern void ui_event_btnSave1( lv_event_t * e);
extern lv_obj_t *ui_btnSave1;
// CUSTOM VARIABLES
extern lv_obj_t *uic_settingsScreen2;
extern lv_obj_t *uic_sldBrightness;
extern lv_obj_t *uic_arcMotorPWM;
extern lv_obj_t *uic_swMotorTest;
extern lv_obj_t *uic_lblPWM;
extern lv_obj_t *uic_lblRPM;
extern lv_obj_t *uic_arcTestSpeed;
extern lv_obj_t *uic_swSpeedTest;
extern lv_obj_t *uic_lblTestSpeed;
extern lv_obj_t *uic_panelReset;
extern lv_obj_t *uic_btnResetYes;
extern lv_obj_t *uic_btnResetNo;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

