// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: Valmar_Screen

#ifndef UI_SETTINGSSCREEN4_H
#define UI_SETTINGSSCREEN4_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_settingsScreen4
extern void ui_settingsScreen4_screen_init(void);
extern void ui_settingsScreen4_screen_destroy(void);
extern lv_obj_t *ui_settingsScreen4;
extern void ui_event_chkStallProtection( lv_event_t * e);
extern lv_obj_t *ui_chkStallProtection;
extern lv_obj_t *ui_Label27;
extern void ui_event_btnBack2( lv_event_t * e);
extern lv_obj_t *ui_btnBack2;
extern void ui_event_ddStallDelay( lv_event_t * e);
extern lv_obj_t *ui_ddStallDelay;
extern lv_obj_t *ui_Label30;
// CUSTOM VARIABLES
extern lv_obj_t *uic_settingsScreen4;
extern lv_obj_t *uic_chkStallProtection;
extern lv_obj_t *uic_ddStallDelay;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

