// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: Valmar_Screen

#ifndef UI_SETTINGSSCREEN1_H
#define UI_SETTINGSSCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_settingsScreen1
extern void ui_settingsScreen1_screen_init(void);
extern void ui_settingsScreen1_screen_destroy(void);
extern lv_obj_t *ui_settingsScreen1;
extern void ui_event_btnBack( lv_event_t * e);
extern lv_obj_t *ui_btnBack;
extern void ui_event_btnSave( lv_event_t * e);
extern lv_obj_t *ui_btnSave;
extern void ui_event_spnWidth( lv_event_t * e);
extern lv_obj_t *ui_spnWidth;
extern void ui_event_spnRuns( lv_event_t * e);
extern lv_obj_t *ui_spnRuns;
extern void ui_event_btnWidthPlus( lv_event_t * e);
extern lv_obj_t *ui_btnWidthPlus;
extern lv_obj_t *ui_Label17;
extern void ui_event_btnWidthPlus1( lv_event_t * e);
extern lv_obj_t *ui_btnWidthPlus1;
extern lv_obj_t *ui_Label18;
extern lv_obj_t *ui_Label34;
extern lv_obj_t *ui_Label35;
extern void ui_event_btnWidthPlus2( lv_event_t * e);
extern lv_obj_t *ui_btnWidthPlus2;
extern lv_obj_t *ui_Label31;
extern void ui_event_btnWidthPlus3( lv_event_t * e);
extern lv_obj_t *ui_btnWidthPlus3;
extern lv_obj_t *ui_Label33;
extern void ui_event_btnPage1( lv_event_t * e);
extern lv_obj_t *ui_btnPage1;
// CUSTOM VARIABLES
extern lv_obj_t *uic_settingsScreen1;
extern lv_obj_t *uic_spnWidth;
extern lv_obj_t *uic_spnRuns;
extern lv_obj_t *uic_btnWidthPlus;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

