// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: Valmar_Screen

#ifndef UI_SETTINGSSCREEN2_H
#define UI_SETTINGSSCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_settingsScreen2
extern void ui_settingsScreen2_screen_init(void);
extern void ui_settingsScreen2_screen_destroy(void);
extern lv_obj_t *ui_settingsScreen2;
extern lv_obj_t *ui_Label32;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_lblVersion;
extern lv_obj_t *ui_lblVersion1;
extern void ui_event_btnCalibrate6( lv_event_t * e);
extern lv_obj_t *ui_btnCalibrate6;
extern void ui_event_btnPage4( lv_event_t * e);
extern lv_obj_t *ui_btnPage4;
extern void ui_event_btnPairing( lv_event_t * e);
extern lv_obj_t *ui_btnPairing;
extern lv_obj_t *ui_Label24;
extern void ui_event_btnScreenFirmware( lv_event_t * e);
extern lv_obj_t *ui_btnScreenFirmware;
extern lv_obj_t *ui_Label27;
extern void ui_event_btnControllerFirmware( lv_event_t * e);
extern lv_obj_t *ui_btnControllerFirmware;
extern lv_obj_t *ui_Label28;
extern lv_obj_t *ui_Label29;
extern lv_obj_t *ui_panelFirmware;
extern lv_obj_t *ui_lblFirmwareWarning;
extern lv_obj_t *ui_Image6;
extern void ui_event_btnFirmwareOK( lv_event_t * e);
extern lv_obj_t *ui_btnFirmwareOK;
extern lv_obj_t *ui_Label30;
// CUSTOM VARIABLES
extern lv_obj_t *uic_settingsScreen2;
extern lv_obj_t *uic_lblVersion;
extern lv_obj_t *uic_btnPairing;
extern lv_obj_t *uic_btnScreenFirmware;
extern lv_obj_t *uic_btnControllerFirmware;
extern lv_obj_t *uic_panelFirmware;
extern lv_obj_t *uic_lblFirmwareWarning;
extern lv_obj_t *uic_btnFirmwareOK;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

