// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: Valmar_Screen

#ifndef UI_SPLASHSCREEN_H
#define UI_SPLASHSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_splashScreen
extern void ui_splashScreen_screen_init(void);
extern void ui_splashScreen_screen_destroy(void);
extern void ui_event_splashScreen( lv_event_t * e);
extern lv_obj_t *ui_splashScreen;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

