// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: Valmar_Screen

#include "ui.h"

lv_obj_t *uic_swCalibrate;
lv_obj_t *uic_txtCalWeight;
lv_obj_t *uic_calibrationScreen;
lv_obj_t *ui_calibrationScreen = NULL;lv_obj_t *ui_Keyboard1 = NULL;lv_obj_t *ui_btnCalibrate2 = NULL;lv_obj_t *ui_txtCalWeight = NULL;lv_obj_t *ui_swCalibrate = NULL;
// event funtions
void ui_event_Keyboard1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_READY) {
      calibrationInput( e );
      _ui_state_modify( ui_swCalibrate, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
      _ui_screen_change( &ui_runScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_runScreen_screen_init);
}
}

void ui_event_btnCalibrate2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_screen_change( &ui_runScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_runScreen_screen_init);
}
}

void ui_event_swCalibrate( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      calSwitchToggle( e );
}
}

// build funtions

void ui_calibrationScreen_screen_init(void)
{
ui_calibrationScreen = lv_obj_create(NULL);
lv_obj_remove_flag( ui_calibrationScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_calibrationScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_calibrationScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Keyboard1 = lv_keyboard_create(ui_calibrationScreen);
lv_keyboard_set_mode(ui_Keyboard1,LV_KEYBOARD_MODE_NUMBER);
lv_obj_set_width( ui_Keyboard1, 442);
lv_obj_set_height( ui_Keyboard1, 151);
lv_obj_set_x( ui_Keyboard1, 0 );
lv_obj_set_y( ui_Keyboard1, 33 );
lv_obj_set_align( ui_Keyboard1, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_Keyboard1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Keyboard1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_object_set_themeable_style_property(ui_Keyboard1, LV_PART_ITEMS| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_valmarRed);
ui_object_set_themeable_style_property(ui_Keyboard1, LV_PART_ITEMS| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_valmarRed);
ui_object_set_themeable_style_property(ui_Keyboard1, LV_PART_ITEMS| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_spinboxOuline);
ui_object_set_themeable_style_property(ui_Keyboard1, LV_PART_ITEMS| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_spinboxOuline);
lv_obj_set_style_border_width(ui_Keyboard1, 3, LV_PART_ITEMS| LV_STATE_DEFAULT);

ui_btnCalibrate2 = lv_button_create(ui_calibrationScreen);
lv_obj_set_width( ui_btnCalibrate2, 50);
lv_obj_set_height( ui_btnCalibrate2, 50);
lv_obj_set_x( ui_btnCalibrate2, -186 );
lv_obj_set_y( ui_btnCalibrate2, -80 );
lv_obj_set_align( ui_btnCalibrate2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnCalibrate2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_btnCalibrate2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnCalibrate2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnCalibrate2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( ui_btnCalibrate2, &ui_img_valmar_back_png, LV_PART_MAIN | LV_STATE_DEFAULT );
ui_object_set_themeable_style_property(ui_btnCalibrate2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_IMAGE_RECOLOR, _ui_theme_color_valmarRed);
ui_object_set_themeable_style_property(ui_btnCalibrate2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_IMAGE_RECOLOR_OPA, _ui_theme_alpha_valmarRed);
ui_object_set_themeable_style_property(ui_btnCalibrate2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_spinboxOuline);
ui_object_set_themeable_style_property(ui_btnCalibrate2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_spinboxOuline);
lv_obj_set_style_border_width(ui_btnCalibrate2, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_txtCalWeight = lv_textarea_create(ui_calibrationScreen);
lv_obj_set_width( ui_txtCalWeight, 216);
lv_obj_set_height( ui_txtCalWeight, LV_SIZE_CONTENT);   /// 76
lv_obj_set_x( ui_txtCalWeight, -14 );
lv_obj_set_y( ui_txtCalWeight, -82 );
lv_obj_set_align( ui_txtCalWeight, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_txtCalWeight,"lbs");
lv_textarea_set_one_line(ui_txtCalWeight,true);
lv_obj_set_style_text_font(ui_txtCalWeight, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_txtCalWeight, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_txtCalWeight, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_swCalibrate = lv_switch_create(ui_calibrationScreen);
lv_obj_set_width( ui_swCalibrate, 100);
lv_obj_set_height( ui_swCalibrate, 50);
lv_obj_set_x( ui_swCalibrate, 156 );
lv_obj_set_y( ui_swCalibrate, -85 );
lv_obj_set_align( ui_swCalibrate, LV_ALIGN_CENTER );

ui_object_set_themeable_style_property(ui_swCalibrate, LV_PART_INDICATOR| LV_STATE_CHECKED, LV_STYLE_BG_COLOR, _ui_theme_color_valmarRed);
ui_object_set_themeable_style_property(ui_swCalibrate, LV_PART_INDICATOR| LV_STATE_CHECKED, LV_STYLE_BG_OPA, _ui_theme_alpha_valmarRed);

lv_keyboard_set_textarea(ui_Keyboard1,ui_txtCalWeight);
lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnCalibrate2, ui_event_btnCalibrate2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_swCalibrate, ui_event_swCalibrate, LV_EVENT_ALL, NULL);
uic_calibrationScreen = ui_calibrationScreen;
uic_txtCalWeight = ui_txtCalWeight;
uic_swCalibrate = ui_swCalibrate;

}

void ui_calibrationScreen_screen_destroy(void)
{
   if (ui_calibrationScreen) lv_obj_del(ui_calibrationScreen);

// NULL screen variables
uic_calibrationScreen= NULL;
ui_calibrationScreen= NULL;
ui_Keyboard1= NULL;
ui_btnCalibrate2= NULL;
uic_txtCalWeight= NULL;
ui_txtCalWeight= NULL;
uic_swCalibrate= NULL;
ui_swCalibrate= NULL;

}
