// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: Valmar_Screen
#include <Arduino.h>
#include "globals.h"
#include "ui.h"
#include "comms.h"

extern IncomingData replyData;

void calibrationInput(lv_event_t * e)
{
	const char *text = lv_textarea_get_text(ui_txtCalWeight);
	
	if (text && strlen(text) > 0) {
		calibrationWeight = atof(text);
		Serial.printf("Calibration Weight %.3f\n", calibrationWeight);
		calibrationMode = false;
	}
}

void calSwitchToggle(lv_event_t * e)
{
	if (lv_obj_has_state(ui_swCalibrate, LV_STATE_CHECKED)) {
		calibrationMode = true;
		
	} else {
		calibrationMode = false;
	}

	replyData.calibrationMode = calibrationMode;
	DBG_PRINT("Calibration mode toggled to: ");
    DBG_PRINTLN(calibrationMode ? "ON" : "OFF");
}

void rateChange(lv_event_t * e)
{
	int seedingRateRawValue = lv_spinbox_get_value(ui_spinboxRate);
	seedingRate = seedingRateRawValue / 10.0f;

	Serial.printf("Seeding Rate: %.1f\n", seedingRate);
}

void backlightControl(lv_event_t * e)
{
	int backlightVal = lv_arc_get_value(ui_arcBacklight);
	ledcWrite(0, backlightVal);  // 50% brightness
}

