// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: Valmar_Screen

#include "ui.h"

lv_obj_t *uic_infoScreen;
lv_obj_t *ui_infoScreen = NULL;lv_obj_t *ui_btnCalibrate4 = NULL;lv_obj_t *ui_Label17 = NULL;lv_obj_t *ui_Label18 = NULL;
// event funtions
void ui_event_btnCalibrate4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_screen_change( &ui_runScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_runScreen_screen_init);
}
}

// build funtions

void ui_infoScreen_screen_init(void)
{
ui_infoScreen = lv_obj_create(NULL);
lv_obj_remove_flag( ui_infoScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_btnCalibrate4 = lv_button_create(ui_infoScreen);
lv_obj_set_width( ui_btnCalibrate4, 50);
lv_obj_set_height( ui_btnCalibrate4, 50);
lv_obj_set_x( ui_btnCalibrate4, -186 );
lv_obj_set_y( ui_btnCalibrate4, -80 );
lv_obj_set_align( ui_btnCalibrate4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnCalibrate4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_btnCalibrate4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnCalibrate4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnCalibrate4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( ui_btnCalibrate4, &ui_img_valmar_back_png, LV_PART_MAIN | LV_STATE_DEFAULT );
ui_object_set_themeable_style_property(ui_btnCalibrate4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_IMAGE_RECOLOR, _ui_theme_color_valmarRed);
ui_object_set_themeable_style_property(ui_btnCalibrate4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_IMAGE_RECOLOR_OPA, _ui_theme_alpha_valmarRed);
ui_object_set_themeable_style_property(ui_btnCalibrate4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_spinboxOuline);
ui_object_set_themeable_style_property(ui_btnCalibrate4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_spinboxOuline);
lv_obj_set_style_border_width(ui_btnCalibrate4, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label17 = lv_label_create(ui_infoScreen);
lv_obj_set_width( ui_Label17, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label17, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label17, -50 );
lv_obj_set_y( ui_Label17, 0 );
lv_obj_set_align( ui_Label17, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label17,"calibrationMode: \ncalibrationRevs: \ncalibrationWeight: \ncorrectionFactor: ");
lv_obj_set_style_text_align(ui_Label17, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label18 = lv_label_create(ui_infoScreen);
lv_obj_set_width( ui_Label18, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label18, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label18, 50 );
lv_obj_set_y( ui_Label18, 0 );
lv_obj_set_align( ui_Label18, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label18,"0\n0\n0\n0");
lv_obj_set_style_text_align(ui_Label18, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_btnCalibrate4, ui_event_btnCalibrate4, LV_EVENT_ALL, NULL);
uic_infoScreen = ui_infoScreen;

}

void ui_infoScreen_screen_destroy(void)
{
   if (ui_infoScreen) lv_obj_del(ui_infoScreen);

// NULL screen variables
uic_infoScreen= NULL;
ui_infoScreen= NULL;
ui_btnCalibrate4= NULL;
ui_Label17= NULL;
ui_Label18= NULL;

}
