// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: Valmar_Screen

#include "ui.h"

lv_obj_t *uic_workLED;
lv_obj_t *uic_lblRate;
lv_obj_t *uic_lblShaftRPM;
lv_obj_t *uic_lblSpeed;
lv_obj_t *uic_lblNumSats;
lv_obj_t *uic_imgGPSFix;
lv_obj_t *uic_btnInfo;
lv_obj_t *uic_btnSettings;
lv_obj_t *uic_btnCalibrate;
lv_obj_t *uic_spinboxRate;
lv_obj_t *uic_lblTime;
lv_obj_t *uic_runScreen;
lv_obj_t *ui_runScreen = NULL;lv_obj_t *ui_Container1 = NULL;lv_obj_t *ui_lblTime = NULL;lv_obj_t *ui_containerRate = NULL;lv_obj_t *ui_spinboxRate = NULL;lv_obj_t *ui_btnPlus = NULL;lv_obj_t *ui_Container2 = NULL;lv_obj_t *ui_Label3 = NULL;lv_obj_t *ui_btnMinus = NULL;lv_obj_t *ui_Container3 = NULL;lv_obj_t *ui_Label4 = NULL;lv_obj_t *ui_Label5 = NULL;lv_obj_t *ui_btnCalibrate = NULL;lv_obj_t *ui_btnSettings = NULL;lv_obj_t *ui_btnInfo = NULL;lv_obj_t *ui_imgGPSFix = NULL;lv_obj_t *ui_lblNumSats = NULL;lv_obj_t *ui_Image4 = NULL;lv_obj_t *ui_Container4 = NULL;lv_obj_t *ui_Container5 = NULL;lv_obj_t *ui_Container6 = NULL;lv_obj_t *ui_Container7 = NULL;lv_obj_t *ui_Label6 = NULL;lv_obj_t *ui_Label7 = NULL;lv_obj_t *ui_Label8 = NULL;lv_obj_t *ui_lblSpeed = NULL;lv_obj_t *ui_lblShaftRPM = NULL;lv_obj_t *ui_lblRate = NULL;lv_obj_t *ui_Container8 = NULL;lv_obj_t *ui_Label1 = NULL;lv_obj_t *ui_workLED = NULL;
// event funtions
void ui_event_runScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      _ui_screen_delete( &ui_splashScreen);
}
}

void ui_event_spinboxRate( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      rateChange( e );
}
}

void ui_event_btnPlus( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_spinbox_step( ui_spinboxRate, 1);
}
if ( event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
      _ui_spinbox_step( ui_spinboxRate, 1);
}
}

void ui_event_btnMinus( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_spinbox_step( ui_spinboxRate, -1);
}
if ( event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
      _ui_spinbox_step( ui_spinboxRate, -1);
}
}

void ui_event_btnCalibrate( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_screen_change( &ui_calibrationScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_calibrationScreen_screen_init);
}
}

void ui_event_btnSettings( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_screen_change( &ui_settingsScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_settingsScreen_screen_init);
}
}

void ui_event_btnInfo( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_screen_change( &ui_infoScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_infoScreen_screen_init);
}
}

// build funtions

void ui_runScreen_screen_init(void)
{
ui_runScreen = lv_obj_create(NULL);
lv_obj_remove_flag( ui_runScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_runScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_runScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container1 = lv_obj_create(ui_runScreen);
lv_obj_remove_style_all(ui_Container1);
lv_obj_set_width( ui_Container1, 480);
lv_obj_set_height( ui_Container1, 1);
lv_obj_set_x( ui_Container1, 0 );
lv_obj_set_y( ui_Container1, -110 );
lv_obj_set_align( ui_Container1, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Container1, lv_color_hex(0x9C3029), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Container1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblTime = lv_label_create(ui_runScreen);
lv_obj_set_width( ui_lblTime, LV_SIZE_CONTENT);  /// 5
lv_obj_set_height( ui_lblTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblTime, 196 );
lv_obj_set_y( ui_lblTime, -121 );
lv_obj_set_align( ui_lblTime, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblTime,"00:00:00");
lv_obj_set_style_text_align(ui_lblTime, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblTime, &ui_font_VeraMono, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_containerRate = lv_obj_create(ui_runScreen);
lv_obj_remove_style_all(ui_containerRate);
lv_obj_set_width( ui_containerRate, 476);
lv_obj_set_height( ui_containerRate, 165);
lv_obj_set_x( ui_containerRate, 0 );
lv_obj_set_y( ui_containerRate, -25 );
lv_obj_set_align( ui_containerRate, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_containerRate, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_spinboxRate = lv_spinbox_create(ui_containerRate);
lv_obj_set_width( ui_spinboxRate, 314);
lv_obj_set_height( ui_spinboxRate, 160);
lv_obj_set_align( ui_spinboxRate, LV_ALIGN_CENTER );
lv_spinbox_set_digit_format( ui_spinboxRate, 3, 2);
lv_spinbox_set_range( ui_spinboxRate, 0,999 );
lv_spinbox_set_cursor_pos(ui_spinboxRate, 1 - 1);
lv_obj_set_style_bg_color(ui_spinboxRate, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_spinboxRate, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_spinboxRate, &ui_font_ConsolaMono, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_spinboxRate, lv_color_hex(0x101418), LV_PART_CURSOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_spinboxRate, 0, LV_PART_CURSOR| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_spinboxRate, LV_PART_CURSOR| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_valmarRed);
ui_object_set_themeable_style_property(ui_spinboxRate, LV_PART_CURSOR| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_valmarRed);
lv_obj_set_style_border_width(ui_spinboxRate, 10, LV_PART_CURSOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_spinboxRate, LV_BORDER_SIDE_BOTTOM, LV_PART_CURSOR| LV_STATE_DEFAULT);

ui_btnPlus = lv_button_create(ui_containerRate);
lv_obj_set_width( ui_btnPlus, 75);
lv_obj_set_height( ui_btnPlus, 75);
lv_obj_set_x( ui_btnPlus, 198 );
lv_obj_set_y( ui_btnPlus, -43 );
lv_obj_set_align( ui_btnPlus, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnPlus, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_btnPlus, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_btnPlus, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_valmarRed);
ui_object_set_themeable_style_property(ui_btnPlus, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_valmarRed);

ui_Container2 = lv_obj_create(ui_btnPlus);
lv_obj_remove_style_all(ui_Container2);
lv_obj_set_width( ui_Container2, 65);
lv_obj_set_height( ui_Container2, 65);
lv_obj_set_align( ui_Container2, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Container2, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Container2, lv_color_hex(0x3B3B3B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Container2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_btnPlus);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, 0 );
lv_obj_set_y( ui_Label3, 5 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"+");
lv_obj_set_style_text_font(ui_Label3, &ui_font_ConsolaMono, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_btnMinus = lv_button_create(ui_containerRate);
lv_obj_set_width( ui_btnMinus, 75);
lv_obj_set_height( ui_btnMinus, 75);
lv_obj_set_x( ui_btnMinus, 198 );
lv_obj_set_y( ui_btnMinus, 42 );
lv_obj_set_align( ui_btnMinus, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnMinus, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_btnMinus, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_btnMinus, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_valmarRed);
ui_object_set_themeable_style_property(ui_btnMinus, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_valmarRed);

ui_Container3 = lv_obj_create(ui_btnMinus);
lv_obj_remove_style_all(ui_Container3);
lv_obj_set_width( ui_Container3, 65);
lv_obj_set_height( ui_Container3, 65);
lv_obj_set_align( ui_Container3, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Container3, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Container3, lv_color_hex(0x3B3B3B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Container3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4 = lv_label_create(ui_btnMinus);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, 0 );
lv_obj_set_y( ui_Label4, 4 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"-");
lv_obj_set_style_text_font(ui_Label4, &ui_font_ConsolaMono, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label5 = lv_label_create(ui_containerRate);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, 0 );
lv_obj_set_y( ui_Label5, -69 );
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"RATE LBS/AC");
lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_btnCalibrate = lv_button_create(ui_runScreen);
lv_obj_set_width( ui_btnCalibrate, 50);
lv_obj_set_height( ui_btnCalibrate, 50);
lv_obj_set_x( ui_btnCalibrate, -186 );
lv_obj_set_y( ui_btnCalibrate, -80 );
lv_obj_set_align( ui_btnCalibrate, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnCalibrate, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_btnCalibrate, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnCalibrate, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnCalibrate, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( ui_btnCalibrate, &ui_img_valmar_cal_png, LV_PART_MAIN | LV_STATE_DEFAULT );
ui_object_set_themeable_style_property(ui_btnCalibrate, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_IMAGE_RECOLOR, _ui_theme_color_valmarRed);
ui_object_set_themeable_style_property(ui_btnCalibrate, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_IMAGE_RECOLOR_OPA, _ui_theme_alpha_valmarRed);
ui_object_set_themeable_style_property(ui_btnCalibrate, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_spinboxOuline);
ui_object_set_themeable_style_property(ui_btnCalibrate, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_spinboxOuline);
lv_obj_set_style_border_width(ui_btnCalibrate, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_btnSettings = lv_button_create(ui_runScreen);
lv_obj_set_width( ui_btnSettings, 50);
lv_obj_set_height( ui_btnSettings, 50);
lv_obj_set_x( ui_btnSettings, -186 );
lv_obj_set_y( ui_btnSettings, -25 );
lv_obj_set_align( ui_btnSettings, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnSettings, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_btnSettings, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnSettings, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnSettings, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( ui_btnSettings, &ui_img_1811295523, LV_PART_MAIN | LV_STATE_DEFAULT );
ui_object_set_themeable_style_property(ui_btnSettings, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_IMAGE_RECOLOR, _ui_theme_color_valmarRed);
ui_object_set_themeable_style_property(ui_btnSettings, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_IMAGE_RECOLOR_OPA, _ui_theme_alpha_valmarRed);
ui_object_set_themeable_style_property(ui_btnSettings, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_spinboxOuline);
ui_object_set_themeable_style_property(ui_btnSettings, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_spinboxOuline);
lv_obj_set_style_border_width(ui_btnSettings, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_btnInfo = lv_button_create(ui_runScreen);
lv_obj_set_width( ui_btnInfo, 50);
lv_obj_set_height( ui_btnInfo, 50);
lv_obj_set_x( ui_btnInfo, -186 );
lv_obj_set_y( ui_btnInfo, 30 );
lv_obj_set_align( ui_btnInfo, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnInfo, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_btnInfo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnInfo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnInfo, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( ui_btnInfo, &ui_img_787606558, LV_PART_MAIN | LV_STATE_DEFAULT );
ui_object_set_themeable_style_property(ui_btnInfo, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_IMAGE_RECOLOR, _ui_theme_color_valmarRed);
ui_object_set_themeable_style_property(ui_btnInfo, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_IMAGE_RECOLOR_OPA, _ui_theme_alpha_valmarRed);
ui_object_set_themeable_style_property(ui_btnInfo, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_spinboxOuline);
ui_object_set_themeable_style_property(ui_btnInfo, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_spinboxOuline);
lv_obj_set_style_border_width(ui_btnInfo, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_imgGPSFix = lv_image_create(ui_runScreen);
lv_image_set_src(ui_imgGPSFix, &ui_img_639977379);
lv_obj_set_width( ui_imgGPSFix, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_imgGPSFix, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_imgGPSFix, 93 );
lv_obj_set_y( ui_imgGPSFix, -120 );
lv_obj_set_align( ui_imgGPSFix, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_imgGPSFix, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_imgGPSFix, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_imgGPSFix, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_valmarRed);
ui_object_set_themeable_style_property(ui_imgGPSFix, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_valmarRed);

ui_lblNumSats = lv_label_create(ui_runScreen);
lv_obj_set_width( ui_lblNumSats, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblNumSats, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblNumSats, 119 );
lv_obj_set_y( ui_lblNumSats, -121 );
lv_obj_set_align( ui_lblNumSats, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblNumSats,"00");
lv_obj_set_style_text_align(ui_lblNumSats, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblNumSats, &ui_font_VeraMono, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image4 = lv_image_create(ui_runScreen);
lv_image_set_src(ui_Image4, &ui_img_232107149);
lv_obj_set_width( ui_Image4, LV_SIZE_CONTENT);  /// 25
lv_obj_set_height( ui_Image4, LV_SIZE_CONTENT);   /// 25
lv_obj_set_x( ui_Image4, 145 );
lv_obj_set_y( ui_Image4, -122 );
lv_obj_set_align( ui_Image4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image4, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_Image4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_Image4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_valmarRed);
ui_object_set_themeable_style_property(ui_Image4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_valmarRed);

ui_Container4 = lv_obj_create(ui_runScreen);
lv_obj_remove_style_all(ui_Container4);
lv_obj_set_width( ui_Container4, 314);
lv_obj_set_height( ui_Container4, 59);
lv_obj_set_x( ui_Container4, 0 );
lv_obj_set_y( ui_Container4, 94 );
lv_obj_set_align( ui_Container4, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Container4, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_Container4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_valmarRed);
ui_object_set_themeable_style_property(ui_Container4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_valmarRed);
ui_object_set_themeable_style_property(ui_Container4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_spinboxOuline);
ui_object_set_themeable_style_property(ui_Container4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_spinboxOuline);
lv_obj_set_style_border_width(ui_Container4, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container5 = lv_obj_create(ui_Container4);
lv_obj_remove_style_all(ui_Container5);
lv_obj_set_width( ui_Container5, 80);
lv_obj_set_height( ui_Container5, 48);
lv_obj_set_x( ui_Container5, -100 );
lv_obj_set_y( ui_Container5, 0 );
lv_obj_set_align( ui_Container5, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Container5, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Container5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Container5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Container5, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container6 = lv_obj_create(ui_Container4);
lv_obj_remove_style_all(ui_Container6);
lv_obj_set_width( ui_Container6, 80);
lv_obj_set_height( ui_Container6, 48);
lv_obj_set_align( ui_Container6, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Container6, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Container6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Container6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Container6, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container7 = lv_obj_create(ui_Container4);
lv_obj_remove_style_all(ui_Container7);
lv_obj_set_width( ui_Container7, 80);
lv_obj_set_height( ui_Container7, 48);
lv_obj_set_x( ui_Container7, 100 );
lv_obj_set_y( ui_Container7, 0 );
lv_obj_set_align( ui_Container7, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Container7, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Container7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Container7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Container7, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label6 = lv_label_create(ui_Container4);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, -100 );
lv_obj_set_y( ui_Label6, -15 );
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"MPH");

ui_Label7 = lv_label_create(ui_Container4);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label7, 0 );
lv_obj_set_y( ui_Label7, -15 );
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"Shaft RPM");

ui_Label8 = lv_label_create(ui_Container4);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label8, 100 );
lv_obj_set_y( ui_Label8, -15 );
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"Rate");

ui_lblSpeed = lv_label_create(ui_Container4);
lv_obj_set_width( ui_lblSpeed, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblSpeed, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblSpeed, -100 );
lv_obj_set_y( ui_lblSpeed, 10 );
lv_obj_set_align( ui_lblSpeed, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblSpeed,"");
lv_obj_set_style_text_align(ui_lblSpeed, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblSpeed, &ui_font_ConsolaMono30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblShaftRPM = lv_label_create(ui_Container4);
lv_obj_set_width( ui_lblShaftRPM, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblShaftRPM, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblShaftRPM, 0 );
lv_obj_set_y( ui_lblShaftRPM, 10 );
lv_obj_set_align( ui_lblShaftRPM, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblShaftRPM,"");
lv_obj_set_style_text_align(ui_lblShaftRPM, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblShaftRPM, &ui_font_ConsolaMono30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblRate = lv_label_create(ui_Container4);
lv_obj_set_width( ui_lblRate, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblRate, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblRate, 100 );
lv_obj_set_y( ui_lblRate, 10 );
lv_obj_set_align( ui_lblRate, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblRate,"");
lv_obj_set_style_text_align(ui_lblRate, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblRate, &ui_font_ConsolaMono30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container8 = lv_obj_create(ui_runScreen);
lv_obj_remove_style_all(ui_Container8);
lv_obj_set_width( ui_Container8, 75);
lv_obj_set_height( ui_Container8, 59);
lv_obj_set_x( ui_Container8, 198 );
lv_obj_set_y( ui_Container8, 94 );
lv_obj_set_align( ui_Container8, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Container8, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_Container8, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_valmarRed);
ui_object_set_themeable_style_property(ui_Container8, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_valmarRed);
ui_object_set_themeable_style_property(ui_Container8, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_spinboxOuline);
ui_object_set_themeable_style_property(ui_Container8, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_spinboxOuline);
lv_obj_set_style_border_width(ui_Container8, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Container8);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, 0 );
lv_obj_set_y( ui_Label1, -15 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"Work");

ui_workLED = lv_obj_create(ui_runScreen);
lv_obj_set_width( ui_workLED, 30);
lv_obj_set_height( ui_workLED, 30);
lv_obj_set_x( ui_workLED, 198 );
lv_obj_set_y( ui_workLED, 104 );
lv_obj_set_align( ui_workLED, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_workLED, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_workLED, 25, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_workLED, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_workLED, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_workLED, lv_color_hex(0x0A6600), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_workLED, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_workLED, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_workLED, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_workLED, lv_color_hex(0x34861F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_workLED, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_workLED, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_workLED, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_workLED, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_workLED, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_workLED, 25, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_bg_color(ui_workLED, lv_color_hex(0x00C73E), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_bg_opa(ui_workLED, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_border_color(ui_workLED, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_border_opa(ui_workLED, 0, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_shadow_color(ui_workLED, lv_color_hex(0x00F20F), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_shadow_opa(ui_workLED, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_shadow_width(ui_workLED, 30, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_shadow_spread(ui_workLED, 2, LV_PART_MAIN| LV_STATE_USER_1);

lv_obj_add_event_cb(ui_spinboxRate, ui_event_spinboxRate, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnPlus, ui_event_btnPlus, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnMinus, ui_event_btnMinus, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnCalibrate, ui_event_btnCalibrate, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnSettings, ui_event_btnSettings, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnInfo, ui_event_btnInfo, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_runScreen, ui_event_runScreen, LV_EVENT_ALL, NULL);
uic_runScreen = ui_runScreen;
uic_lblTime = ui_lblTime;
uic_spinboxRate = ui_spinboxRate;
uic_btnCalibrate = ui_btnCalibrate;
uic_btnSettings = ui_btnSettings;
uic_btnInfo = ui_btnInfo;
uic_imgGPSFix = ui_imgGPSFix;
uic_lblNumSats = ui_lblNumSats;
uic_lblSpeed = ui_lblSpeed;
uic_lblShaftRPM = ui_lblShaftRPM;
uic_lblRate = ui_lblRate;
uic_workLED = ui_workLED;

}

void ui_runScreen_screen_destroy(void)
{
   if (ui_runScreen) lv_obj_del(ui_runScreen);

// NULL screen variables
uic_runScreen= NULL;
ui_runScreen= NULL;
ui_Container1= NULL;
uic_lblTime= NULL;
ui_lblTime= NULL;
ui_containerRate= NULL;
uic_spinboxRate= NULL;
ui_spinboxRate= NULL;
ui_btnPlus= NULL;
ui_Container2= NULL;
ui_Label3= NULL;
ui_btnMinus= NULL;
ui_Container3= NULL;
ui_Label4= NULL;
ui_Label5= NULL;
uic_btnCalibrate= NULL;
ui_btnCalibrate= NULL;
uic_btnSettings= NULL;
ui_btnSettings= NULL;
uic_btnInfo= NULL;
ui_btnInfo= NULL;
uic_imgGPSFix= NULL;
ui_imgGPSFix= NULL;
uic_lblNumSats= NULL;
ui_lblNumSats= NULL;
ui_Image4= NULL;
ui_Container4= NULL;
ui_Container5= NULL;
ui_Container6= NULL;
ui_Container7= NULL;
ui_Label6= NULL;
ui_Label7= NULL;
ui_Label8= NULL;
uic_lblSpeed= NULL;
ui_lblSpeed= NULL;
uic_lblShaftRPM= NULL;
ui_lblShaftRPM= NULL;
uic_lblRate= NULL;
ui_lblRate= NULL;
ui_Container8= NULL;
ui_Label1= NULL;
uic_workLED= NULL;
ui_workLED= NULL;

}
