// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: Valmar_Screen

#include "ui.h"

lv_obj_t *ui_splashScreen = NULL;
// event funtions
void ui_event_splashScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      _ui_screen_change( &ui_runScreen, LV_SCR_LOAD_ANIM_NONE, 0, 2500, &ui_runScreen_screen_init);
}
}

// build funtions

void ui_splashScreen_screen_init(void)
{
ui_splashScreen = lv_obj_create(NULL);
lv_obj_remove_flag( ui_splashScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_image_src( ui_splashScreen, &ui_img_valmar_valmar2_png, LV_PART_MAIN | LV_STATE_DEFAULT );

lv_obj_add_event_cb(ui_splashScreen, ui_event_splashScreen, LV_EVENT_ALL, NULL);

}

void ui_splashScreen_screen_destroy(void)
{
   if (ui_splashScreen) lv_obj_del(ui_splashScreen);

// NULL screen variables
ui_splashScreen= NULL;

}
