// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: Valmar_Screen

#include "ui.h"

lv_obj_t *uic_ddStallDelay;
lv_obj_t *uic_chkStallProtection;
lv_obj_t *uic_settingsScreen4;
lv_obj_t *ui_settingsScreen4 = NULL;lv_obj_t *ui_chkStallProtection = NULL;lv_obj_t *ui_Label27 = NULL;lv_obj_t *ui_btnBack2 = NULL;lv_obj_t *ui_ddStallDelay = NULL;lv_obj_t *ui_Label30 = NULL;
// event funtions
void ui_event_chkStallProtection( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      stallProtection( e );
}
}

void ui_event_btnBack2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_runScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_runScreen_screen_init);
}
}

void ui_event_ddStallDelay( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      updateStallDelay( e );
}
}

// build funtions

void ui_settingsScreen4_screen_init(void)
{
ui_settingsScreen4 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_settingsScreen4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_settingsScreen4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_settingsScreen4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_chkStallProtection = lv_checkbox_create(ui_settingsScreen4);
lv_checkbox_set_text(ui_chkStallProtection,"Stall Protection");
lv_obj_set_width( ui_chkStallProtection, LV_SIZE_CONTENT);  /// 337
lv_obj_set_height( ui_chkStallProtection, LV_SIZE_CONTENT);   /// 70
lv_obj_set_x( ui_chkStallProtection, 0 );
lv_obj_set_y( ui_chkStallProtection, -12 );
lv_obj_set_align( ui_chkStallProtection, LV_ALIGN_CENTER );
lv_obj_add_state( ui_chkStallProtection, LV_STATE_CHECKED );     /// States
lv_obj_add_flag( ui_chkStallProtection, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_font(ui_chkStallProtection, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_chkStallProtection, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_chkStallProtection, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_chkStallProtection, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_ValmarRed);
ui_object_set_themeable_style_property(ui_chkStallProtection, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_ValmarRed);
ui_object_set_themeable_style_property(ui_chkStallProtection, LV_PART_INDICATOR| LV_STATE_CHECKED, LV_STYLE_BG_COLOR, _ui_theme_color_ValmarRed);
ui_object_set_themeable_style_property(ui_chkStallProtection, LV_PART_INDICATOR| LV_STATE_CHECKED, LV_STYLE_BG_OPA, _ui_theme_alpha_ValmarRed);

ui_Label27 = lv_label_create(ui_settingsScreen4);
lv_obj_set_width( ui_Label27, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label27, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label27, -5 );
lv_obj_set_y( ui_Label27, -118 );
lv_obj_set_align( ui_Label27, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label27,"ADVANCED OPTIONS.\nTHESE OPTIONS TAKE EFFECT IMMEDIATELY!");
lv_obj_set_style_text_align(ui_Label27, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_btnBack2 = lv_button_create(ui_settingsScreen4);
lv_obj_set_width( ui_btnBack2, 50);
lv_obj_set_height( ui_btnBack2, 50);
lv_obj_set_x( ui_btnBack2, -186 );
lv_obj_set_y( ui_btnBack2, -80 );
lv_obj_set_align( ui_btnBack2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnBack2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_btnBack2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnBack2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnBack2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( ui_btnBack2, &ui_img_valmar_back_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_image_recolor(ui_btnBack2, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_recolor_opa(ui_btnBack2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_btnBack2, lv_color_hex(0x293031), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_btnBack2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_btnBack2, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ddStallDelay = lv_dropdown_create(ui_settingsScreen4);
lv_dropdown_set_dir( ui_ddStallDelay, LV_DIR_RIGHT);
lv_dropdown_set_options( ui_ddStallDelay, "200\n300\n400\n500\n600\n700\n800\n900\n1000\n" );
lv_obj_set_width( ui_ddStallDelay, 130);
lv_obj_set_height( ui_ddStallDelay, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ddStallDelay, -25 );
lv_obj_set_y( ui_ddStallDelay, -70 );
lv_obj_set_align( ui_ddStallDelay, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ddStallDelay, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_align(ui_ddStallDelay, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ddStallDelay, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ddStallDelay, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ddStallDelay, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_align(ui_ddStallDelay, LV_TEXT_ALIGN_CENTER, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_text_align(lv_dropdown_get_list(ui_ddStallDelay), LV_TEXT_ALIGN_CENTER,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(lv_dropdown_get_list(ui_ddStallDelay), &lv_font_montserrat_28,  LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(lv_dropdown_get_list(ui_ddStallDelay),  LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_ValmarGrey);
ui_object_set_themeable_style_property(lv_dropdown_get_list(ui_ddStallDelay),  LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_ValmarGrey);

lv_obj_set_style_text_align(lv_dropdown_get_list(ui_ddStallDelay), LV_TEXT_ALIGN_CENTER,  LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(lv_dropdown_get_list(ui_ddStallDelay), &lv_font_montserrat_28,  LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_radius(lv_dropdown_get_list(ui_ddStallDelay), 2,  LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_Label30 = lv_label_create(ui_settingsScreen4);
lv_obj_set_width( ui_Label30, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label30, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label30, -120 );
lv_obj_set_y( ui_Label30, -70 );
lv_obj_set_align( ui_Label30, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label30,"STALL\nDELAY");
lv_obj_set_style_text_align(ui_Label30, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_chkStallProtection, ui_event_chkStallProtection, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnBack2, ui_event_btnBack2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ddStallDelay, ui_event_ddStallDelay, LV_EVENT_ALL, NULL);
uic_settingsScreen4 = ui_settingsScreen4;
uic_chkStallProtection = ui_chkStallProtection;
uic_ddStallDelay = ui_ddStallDelay;

}

void ui_settingsScreen4_screen_destroy(void)
{
   if (ui_settingsScreen4) lv_obj_del(ui_settingsScreen4);

// NULL screen variables
uic_settingsScreen4= NULL;
ui_settingsScreen4= NULL;
uic_chkStallProtection= NULL;
ui_chkStallProtection= NULL;
ui_Label27= NULL;
ui_btnBack2= NULL;
uic_ddStallDelay= NULL;
ui_ddStallDelay= NULL;
ui_Label30= NULL;

}
