// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: Valmar_Screen

#include "ui.h"

lv_obj_t *uic_btnReset;
lv_obj_t *uic_btnFirmwareOK;
lv_obj_t *uic_lblFirmwareWarning;
lv_obj_t *uic_panelFirmware;
lv_obj_t *uic_btnControllerFirmware;
lv_obj_t *uic_btnScreenFirmware;
lv_obj_t *uic_btnPairing;
lv_obj_t *uic_lblVersion;
lv_obj_t *uic_settingsScreen3;
lv_obj_t *ui_settingsScreen3 = NULL;lv_obj_t *ui_Label32 = NULL;lv_obj_t *ui_Label10 = NULL;lv_obj_t *ui_lblVersion = NULL;lv_obj_t *ui_lblVersion1 = NULL;lv_obj_t *ui_btnBack3 = NULL;lv_obj_t *ui_btnPairing = NULL;lv_obj_t *ui_Label24 = NULL;lv_obj_t *ui_btnScreenFirmware = NULL;lv_obj_t *ui_Label27 = NULL;lv_obj_t *ui_btnControllerFirmware = NULL;lv_obj_t *ui_Label28 = NULL;lv_obj_t *ui_Label29 = NULL;lv_obj_t *ui_panelFirmware = NULL;lv_obj_t *ui_lblFirmwareWarning = NULL;lv_obj_t *ui_Image6 = NULL;lv_obj_t *ui_btnFirmwareOK = NULL;lv_obj_t *ui_Label30 = NULL;lv_obj_t *ui_btnReset = NULL;lv_obj_t *ui_Label11 = NULL;
// event funtions
void ui_event_btnBack3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_screen_change( &ui_runScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_runScreen_screen_init);
}
}

void ui_event_btnPairing( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      pairController( e );
      _ui_state_modify( ui_btnPairing, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
}
}

void ui_event_btnScreenFirmware( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      screenFirmware( e );
      _ui_flag_modify( ui_btnFirmwareOK, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_panelFirmware, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_btnControllerFirmware( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      controllerFirmware( e );
      _ui_flag_modify( ui_btnFirmwareOK, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_panelFirmware, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_btnFirmwareOK( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_flag_modify( ui_panelFirmware, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_btnReset( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_flag_modify( ui_panelReset, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

// build funtions

void ui_settingsScreen3_screen_init(void)
{
ui_settingsScreen3 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_settingsScreen3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_settingsScreen3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_settingsScreen3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label32 = lv_label_create(ui_settingsScreen3);
lv_obj_set_width( ui_Label32, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label32, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label32, 110 );
lv_obj_set_y( ui_Label32, 120 );
lv_obj_set_align( ui_Label32, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label32,"Controller Ver:");

ui_Label10 = lv_label_create(ui_settingsScreen3);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label10, -170 );
lv_obj_set_y( ui_Label10, 120 );
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label10,"Screen Ver:");

ui_lblVersion = lv_label_create(ui_settingsScreen3);
lv_obj_set_width( ui_lblVersion, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblVersion, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblVersion, 195 );
lv_obj_set_y( ui_lblVersion, 120 );
lv_obj_set_align( ui_lblVersion, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblVersion,"0.0.0");

ui_lblVersion1 = lv_label_create(ui_settingsScreen3);
lv_obj_set_width( ui_lblVersion1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblVersion1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblVersion1, -100 );
lv_obj_set_y( ui_lblVersion1, 120 );
lv_obj_set_align( ui_lblVersion1, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblVersion1,"0.0.0");

ui_btnBack3 = lv_button_create(ui_settingsScreen3);
lv_obj_set_width( ui_btnBack3, 50);
lv_obj_set_height( ui_btnBack3, 50);
lv_obj_set_x( ui_btnBack3, -186 );
lv_obj_set_y( ui_btnBack3, -80 );
lv_obj_set_align( ui_btnBack3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnBack3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_btnBack3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnBack3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnBack3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( ui_btnBack3, &ui_img_valmar_back_png, LV_PART_MAIN | LV_STATE_DEFAULT );
ui_object_set_themeable_style_property(ui_btnBack3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_IMAGE_RECOLOR, _ui_theme_color_ValmarRed);
ui_object_set_themeable_style_property(ui_btnBack3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_IMAGE_RECOLOR_OPA, _ui_theme_alpha_ValmarRed);
lv_obj_set_style_border_color(ui_btnBack3, lv_color_hex(0x293031), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_btnBack3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_btnBack3, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_btnPairing = lv_button_create(ui_settingsScreen3);
lv_obj_set_width( ui_btnPairing, 120);
lv_obj_set_height( ui_btnPairing, 50);
lv_obj_set_x( ui_btnPairing, 170 );
lv_obj_set_y( ui_btnPairing, -100 );
lv_obj_set_align( ui_btnPairing, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnPairing, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_btnPairing, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_btnPairing, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_ValmarRed);
ui_object_set_themeable_style_property(ui_btnPairing, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_ValmarRed);
lv_obj_set_style_border_color(ui_btnPairing, lv_color_hex(0x293031), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_btnPairing, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_btnPairing, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_btnPairing, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label24 = lv_label_create(ui_btnPairing);
lv_obj_set_width( ui_Label24, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label24, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label24, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label24,"PAIR\nCONTROLLER");

ui_btnScreenFirmware = lv_button_create(ui_settingsScreen3);
lv_obj_set_width( ui_btnScreenFirmware, 120);
lv_obj_set_height( ui_btnScreenFirmware, 50);
lv_obj_set_x( ui_btnScreenFirmware, 170 );
lv_obj_set_y( ui_btnScreenFirmware, -40 );
lv_obj_set_align( ui_btnScreenFirmware, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnScreenFirmware, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_btnScreenFirmware, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_btnScreenFirmware, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_ValmarRed);
ui_object_set_themeable_style_property(ui_btnScreenFirmware, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_ValmarRed);
lv_obj_set_style_border_color(ui_btnScreenFirmware, lv_color_hex(0x293031), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_btnScreenFirmware, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_btnScreenFirmware, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_btnScreenFirmware, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label27 = lv_label_create(ui_btnScreenFirmware);
lv_obj_set_width( ui_Label27, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label27, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label27, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label27,"SCREEN\nFIRMWARE");

ui_btnControllerFirmware = lv_button_create(ui_settingsScreen3);
lv_obj_set_width( ui_btnControllerFirmware, 120);
lv_obj_set_height( ui_btnControllerFirmware, 50);
lv_obj_set_x( ui_btnControllerFirmware, 170 );
lv_obj_set_y( ui_btnControllerFirmware, 20 );
lv_obj_set_align( ui_btnControllerFirmware, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnControllerFirmware, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_btnControllerFirmware, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_btnControllerFirmware, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_ValmarRed);
ui_object_set_themeable_style_property(ui_btnControllerFirmware, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_ValmarRed);
lv_obj_set_style_border_color(ui_btnControllerFirmware, lv_color_hex(0x293031), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_btnControllerFirmware, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_btnControllerFirmware, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_btnControllerFirmware, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label28 = lv_label_create(ui_btnControllerFirmware);
lv_obj_set_width( ui_Label28, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label28, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label28, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label28,"CONTROLLER\nFIRMWARE");

ui_Label29 = lv_label_create(ui_settingsScreen3);
lv_obj_set_width( ui_Label29, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label29, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label29, -20 );
lv_obj_set_y( ui_Label29, -10 );
lv_obj_set_align( ui_Label29, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label29,"Connect to a new rate controller  \n\n\n\nUpdate screen firmware  \n\n\n\nUpdate rate controller firmware   \n\n\n\nReset Screen and rate controller  ");
lv_obj_set_style_text_letter_space(ui_Label29, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Label29, -2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label29, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panelFirmware = lv_obj_create(ui_settingsScreen3);
lv_obj_set_width( ui_panelFirmware, 480);
lv_obj_set_height( ui_panelFirmware, 272);
lv_obj_set_align( ui_panelFirmware, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_panelFirmware, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_remove_flag( ui_panelFirmware, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_panelFirmware, lv_color_hex(0x78110A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_panelFirmware, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_panelFirmware, lv_color_hex(0x293031), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_panelFirmware, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_panelFirmware, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblFirmwareWarning = lv_label_create(ui_panelFirmware);
lv_obj_set_width( ui_lblFirmwareWarning, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblFirmwareWarning, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblFirmwareWarning, 5 );
lv_obj_set_y( ui_lblFirmwareWarning, 5 );
lv_obj_set_align( ui_lblFirmwareWarning, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblFirmwareWarning,"Device set to firmware update mode.\nConnect to WiFi network with name valmar-xxxxx\nwith your mobile device and follow on screen\ninstructions.  Device will reboot when complete.");
lv_obj_set_style_text_align(ui_lblFirmwareWarning, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image6 = lv_image_create(ui_panelFirmware);
lv_image_set_src(ui_Image6, &ui_img_1608339404);
lv_obj_set_width( ui_Image6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image6, 0 );
lv_obj_set_y( ui_Image6, -75 );
lv_obj_set_align( ui_Image6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image6, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_Image6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_btnFirmwareOK = lv_button_create(ui_panelFirmware);
lv_obj_set_width( ui_btnFirmwareOK, 100);
lv_obj_set_height( ui_btnFirmwareOK, 50);
lv_obj_set_x( ui_btnFirmwareOK, 0 );
lv_obj_set_y( ui_btnFirmwareOK, 75 );
lv_obj_set_align( ui_btnFirmwareOK, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnFirmwareOK, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_btnFirmwareOK, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnFirmwareOK, lv_color_hex(0x293031), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnFirmwareOK, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label30 = lv_label_create(ui_btnFirmwareOK);
lv_obj_set_width( ui_Label30, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label30, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label30, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label30,"OK");

ui_btnReset = lv_button_create(ui_settingsScreen3);
lv_obj_set_width( ui_btnReset, 120);
lv_obj_set_height( ui_btnReset, 50);
lv_obj_set_x( ui_btnReset, 170 );
lv_obj_set_y( ui_btnReset, 80 );
lv_obj_set_align( ui_btnReset, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnReset, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_btnReset, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_btnReset, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_ValmarRed);
ui_object_set_themeable_style_property(ui_btnReset, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_ValmarRed);
lv_obj_set_style_border_color(ui_btnReset, lv_color_hex(0x293031), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_btnReset, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_btnReset, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label11 = lv_label_create(ui_btnReset);
lv_obj_set_width( ui_Label11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label11, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label11,"RESET");

lv_obj_add_event_cb(ui_btnBack3, ui_event_btnBack3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnPairing, ui_event_btnPairing, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnScreenFirmware, ui_event_btnScreenFirmware, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnControllerFirmware, ui_event_btnControllerFirmware, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnFirmwareOK, ui_event_btnFirmwareOK, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnReset, ui_event_btnReset, LV_EVENT_ALL, NULL);
uic_settingsScreen3 = ui_settingsScreen3;
uic_lblVersion = ui_lblVersion;
uic_btnPairing = ui_btnPairing;
uic_btnScreenFirmware = ui_btnScreenFirmware;
uic_btnControllerFirmware = ui_btnControllerFirmware;
uic_panelFirmware = ui_panelFirmware;
uic_lblFirmwareWarning = ui_lblFirmwareWarning;
uic_btnFirmwareOK = ui_btnFirmwareOK;
uic_btnReset = ui_btnReset;

}

void ui_settingsScreen3_screen_destroy(void)
{
   if (ui_settingsScreen3) lv_obj_del(ui_settingsScreen3);

// NULL screen variables
uic_settingsScreen3= NULL;
ui_settingsScreen3= NULL;
ui_Label32= NULL;
ui_Label10= NULL;
uic_lblVersion= NULL;
ui_lblVersion= NULL;
ui_lblVersion1= NULL;
ui_btnBack3= NULL;
uic_btnPairing= NULL;
ui_btnPairing= NULL;
ui_Label24= NULL;
uic_btnScreenFirmware= NULL;
ui_btnScreenFirmware= NULL;
ui_Label27= NULL;
uic_btnControllerFirmware= NULL;
ui_btnControllerFirmware= NULL;
ui_Label28= NULL;
ui_Label29= NULL;
uic_panelFirmware= NULL;
ui_panelFirmware= NULL;
uic_lblFirmwareWarning= NULL;
ui_lblFirmwareWarning= NULL;
ui_Image6= NULL;
uic_btnFirmwareOK= NULL;
ui_btnFirmwareOK= NULL;
ui_Label30= NULL;
uic_btnReset= NULL;
ui_btnReset= NULL;
ui_Label11= NULL;

}
