// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: Valmar_Screen

#include "ui.h"

lv_obj_t *uic_btnLock;
lv_obj_t *uic_txtSeedPerRev;
lv_obj_t *uic_btnPage;
lv_obj_t *uic_settingsScreen1;
lv_obj_t *ui_settingsScreen1 = NULL;lv_obj_t *ui_Label9 = NULL;lv_obj_t *ui_btnCalibrate5 = NULL;lv_obj_t *ui_btnPage = NULL;lv_obj_t *ui_Keyboard3 = NULL;lv_obj_t *ui_txtSeedPerRev = NULL;lv_obj_t *ui_btnUnlock = NULL;lv_obj_t *ui_btnLock = NULL;
// event funtions
void ui_event_btnCalibrate5( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_screen_change( &ui_runScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_runScreen_screen_init);
}
}

void ui_event_btnPage( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_screen_change( &ui_settingsScreen2, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_settingsScreen2_screen_init);
}
}

void ui_event_Keyboard3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_READY) {
      seedPerRevManualSet( e );
      _ui_flag_modify( ui_Keyboard3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_btnLock, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_btnUnlock, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_state_modify( ui_txtSeedPerRev, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
}
}

void ui_event_txtSeedPerRev( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_state_modify( ui_txtSeedPerRev, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
}
}

void ui_event_btnUnlock( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_state_modify( ui_txtSeedPerRev, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
      _ui_flag_modify( ui_btnUnlock, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_btnLock, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_Keyboard3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_btnLock( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_state_modify( ui_txtSeedPerRev, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
      _ui_flag_modify( ui_btnUnlock, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_btnLock, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_Keyboard3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

// build funtions

void ui_settingsScreen1_screen_init(void)
{
ui_settingsScreen1 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_settingsScreen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_settingsScreen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_settingsScreen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label9 = lv_label_create(ui_settingsScreen1);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"For manual seedPerRev input.");

ui_btnCalibrate5 = lv_button_create(ui_settingsScreen1);
lv_obj_set_width( ui_btnCalibrate5, 50);
lv_obj_set_height( ui_btnCalibrate5, 50);
lv_obj_set_x( ui_btnCalibrate5, -186 );
lv_obj_set_y( ui_btnCalibrate5, -80 );
lv_obj_set_align( ui_btnCalibrate5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnCalibrate5, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_btnCalibrate5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnCalibrate5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnCalibrate5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( ui_btnCalibrate5, &ui_img_valmar_back_png, LV_PART_MAIN | LV_STATE_DEFAULT );
ui_object_set_themeable_style_property(ui_btnCalibrate5, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_IMAGE_RECOLOR, _ui_theme_color_valmarRed);
ui_object_set_themeable_style_property(ui_btnCalibrate5, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_IMAGE_RECOLOR_OPA, _ui_theme_alpha_valmarRed);
ui_object_set_themeable_style_property(ui_btnCalibrate5, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_spinboxOuline);
ui_object_set_themeable_style_property(ui_btnCalibrate5, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_spinboxOuline);
lv_obj_set_style_border_width(ui_btnCalibrate5, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_btnPage = lv_button_create(ui_settingsScreen1);
lv_obj_set_width( ui_btnPage, 50);
lv_obj_set_height( ui_btnPage, 50);
lv_obj_set_x( ui_btnPage, -186 );
lv_obj_set_y( ui_btnPage, -25 );
lv_obj_set_align( ui_btnPage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnPage, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_btnPage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnPage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnPage, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( ui_btnPage, &ui_img_1504963450, LV_PART_MAIN | LV_STATE_DEFAULT );
ui_object_set_themeable_style_property(ui_btnPage, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_IMAGE_RECOLOR, _ui_theme_color_valmarRed);
ui_object_set_themeable_style_property(ui_btnPage, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_IMAGE_RECOLOR_OPA, _ui_theme_alpha_valmarRed);
ui_object_set_themeable_style_property(ui_btnPage, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_spinboxOuline);
ui_object_set_themeable_style_property(ui_btnPage, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_spinboxOuline);
lv_obj_set_style_border_width(ui_btnPage, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Keyboard3 = lv_keyboard_create(ui_settingsScreen1);
lv_keyboard_set_mode(ui_Keyboard3,LV_KEYBOARD_MODE_NUMBER);
lv_obj_set_width( ui_Keyboard3, 442);
lv_obj_set_height( ui_Keyboard3, 151);
lv_obj_set_x( ui_Keyboard3, 0 );
lv_obj_set_y( ui_Keyboard3, 33 );
lv_obj_set_align( ui_Keyboard3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Keyboard3, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_bg_color(ui_Keyboard3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Keyboard3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_object_set_themeable_style_property(ui_Keyboard3, LV_PART_ITEMS| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_valmarRed);
ui_object_set_themeable_style_property(ui_Keyboard3, LV_PART_ITEMS| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_valmarRed);
ui_object_set_themeable_style_property(ui_Keyboard3, LV_PART_ITEMS| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_spinboxOuline);
ui_object_set_themeable_style_property(ui_Keyboard3, LV_PART_ITEMS| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_spinboxOuline);
lv_obj_set_style_border_width(ui_Keyboard3, 3, LV_PART_ITEMS| LV_STATE_DEFAULT);

ui_txtSeedPerRev = lv_textarea_create(ui_settingsScreen1);
lv_obj_set_width( ui_txtSeedPerRev, 216);
lv_obj_set_height( ui_txtSeedPerRev, LV_SIZE_CONTENT);   /// 76
lv_obj_set_x( ui_txtSeedPerRev, 0 );
lv_obj_set_y( ui_txtSeedPerRev, -82 );
lv_obj_set_align( ui_txtSeedPerRev, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_txtSeedPerRev,"CAL");
lv_textarea_set_one_line(ui_txtSeedPerRev,true);
lv_obj_add_state( ui_txtSeedPerRev, LV_STATE_DISABLED );     /// States
lv_obj_remove_flag( ui_txtSeedPerRev, LV_OBJ_FLAG_CLICK_FOCUSABLE );    /// Flags
lv_obj_set_style_text_align(ui_txtSeedPerRev, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_txtSeedPerRev, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_txtSeedPerRev, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_txtSeedPerRev, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_btnUnlock = lv_button_create(ui_settingsScreen1);
lv_obj_set_width( ui_btnUnlock, 50);
lv_obj_set_height( ui_btnUnlock, 50);
lv_obj_set_x( ui_btnUnlock, 186 );
lv_obj_set_y( ui_btnUnlock, -80 );
lv_obj_set_align( ui_btnUnlock, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnUnlock, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_btnUnlock, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnUnlock, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnUnlock, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( ui_btnUnlock, &ui_img_624051001, LV_PART_MAIN | LV_STATE_DEFAULT );
ui_object_set_themeable_style_property(ui_btnUnlock, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_IMAGE_RECOLOR, _ui_theme_color_valmarRed);
ui_object_set_themeable_style_property(ui_btnUnlock, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_IMAGE_RECOLOR_OPA, _ui_theme_alpha_valmarRed);
ui_object_set_themeable_style_property(ui_btnUnlock, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_spinboxOuline);
ui_object_set_themeable_style_property(ui_btnUnlock, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_spinboxOuline);
lv_obj_set_style_border_width(ui_btnUnlock, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_btnLock = lv_button_create(ui_settingsScreen1);
lv_obj_set_width( ui_btnLock, 50);
lv_obj_set_height( ui_btnLock, 50);
lv_obj_set_x( ui_btnLock, 186 );
lv_obj_set_y( ui_btnLock, -80 );
lv_obj_set_align( ui_btnLock, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnLock, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_btnLock, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnLock, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnLock, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( ui_btnLock, &ui_img_508761420, LV_PART_MAIN | LV_STATE_DEFAULT );
ui_object_set_themeable_style_property(ui_btnLock, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_IMAGE_RECOLOR, _ui_theme_color_valmarRed);
ui_object_set_themeable_style_property(ui_btnLock, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_IMAGE_RECOLOR_OPA, _ui_theme_alpha_valmarRed);
ui_object_set_themeable_style_property(ui_btnLock, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_spinboxOuline);
ui_object_set_themeable_style_property(ui_btnLock, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_spinboxOuline);
lv_obj_set_style_border_width(ui_btnLock, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_btnCalibrate5, ui_event_btnCalibrate5, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnPage, ui_event_btnPage, LV_EVENT_ALL, NULL);
lv_keyboard_set_textarea(ui_Keyboard3,ui_txtSeedPerRev);
lv_obj_add_event_cb(ui_Keyboard3, ui_event_Keyboard3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_txtSeedPerRev, ui_event_txtSeedPerRev, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnUnlock, ui_event_btnUnlock, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnLock, ui_event_btnLock, LV_EVENT_ALL, NULL);
uic_settingsScreen1 = ui_settingsScreen1;
uic_btnPage = ui_btnPage;
uic_txtSeedPerRev = ui_txtSeedPerRev;
uic_btnLock = ui_btnLock;

}

void ui_settingsScreen1_screen_destroy(void)
{
   if (ui_settingsScreen1) lv_obj_del(ui_settingsScreen1);

// NULL screen variables
uic_settingsScreen1= NULL;
ui_settingsScreen1= NULL;
ui_Label9= NULL;
ui_btnCalibrate5= NULL;
uic_btnPage= NULL;
ui_btnPage= NULL;
ui_Keyboard3= NULL;
uic_txtSeedPerRev= NULL;
ui_txtSeedPerRev= NULL;
ui_btnUnlock= NULL;
uic_btnLock= NULL;
ui_btnLock= NULL;

}
