// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: Valmar_Screen

#include "ui.h"

lv_obj_t *uic_btnResetNo;
lv_obj_t *uic_btnResetYes;
lv_obj_t *uic_panelReset;
lv_obj_t *uic_btnFirmwareUpdate;
lv_obj_t *uic_lblCancelButton;
lv_obj_t *uic_btnFirmwareCancel;
lv_obj_t *uic_lblFirmwareWarning;
lv_obj_t *uic_panelFirmware;
lv_obj_t *uic_btnPairing;
lv_obj_t *uic_lblVersion;
lv_obj_t *uic_btnReset;
lv_obj_t *uic_btnControllerFirmware;
lv_obj_t *uic_btnAdvancedOptions;
lv_obj_t *uic_settingsScreen3;
lv_obj_t *ui_settingsScreen3 = NULL;lv_obj_t *ui_btnAdvancedOptions = NULL;lv_obj_t *ui_Label36 = NULL;lv_obj_t *ui_btnControllerFirmware = NULL;lv_obj_t *ui_Label28 = NULL;lv_obj_t *ui_btnReset = NULL;lv_obj_t *ui_Label11 = NULL;lv_obj_t *ui_Label32 = NULL;lv_obj_t *ui_Label10 = NULL;lv_obj_t *ui_lblVersion = NULL;lv_obj_t *ui_lblVersion1 = NULL;lv_obj_t *ui_btnBack3 = NULL;lv_obj_t *ui_btnPairing = NULL;lv_obj_t *ui_Label24 = NULL;lv_obj_t *ui_Label29 = NULL;lv_obj_t *ui_panelFirmware = NULL;lv_obj_t *ui_lblFirmwareWarning = NULL;lv_obj_t *ui_Image6 = NULL;lv_obj_t *ui_btnFirmwareCancel = NULL;lv_obj_t *ui_lblCancelButton = NULL;lv_obj_t *ui_btnFirmwareUpdate = NULL;lv_obj_t *ui_Label6 = NULL;lv_obj_t *ui_panelReset = NULL;lv_obj_t *ui_Label12 = NULL;lv_obj_t *ui_Image5 = NULL;lv_obj_t *ui_btnResetYes = NULL;lv_obj_t *ui_Label13 = NULL;lv_obj_t *ui_btnResetNo = NULL;lv_obj_t *ui_Label2 = NULL;
// event funtions
void ui_event_btnAdvancedOptions( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_screen_change( &ui_settingsScreen4, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_settingsScreen4_screen_init);
}
}

void ui_event_btnControllerFirmware( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_btnFirmwareCancel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_panelFirmware, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_btnReset( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_flag_modify( ui_panelReset, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_btnBack3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_runScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_runScreen_screen_init);
}
}

void ui_event_btnPairing( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      pairController( e );
      _ui_state_modify( ui_btnPairing, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
}
}

void ui_event_btnFirmwareCancel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_flag_modify( ui_panelFirmware, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_state_modify( ui_btnFirmwareUpdate, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
      _ui_label_set_property(ui_lblCancelButton, _UI_LABEL_PROPERTY_TEXT, "CANCEL");
}
}

void ui_event_btnFirmwareUpdate( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      controllerFirmware( e );
      _ui_state_modify( ui_btnFirmwareUpdate, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
      _ui_state_modify( ui_btnFirmwareCancel, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
}
}

void ui_event_btnResetYes( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      initReset( e );
}
}

void ui_event_btnResetNo( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_flag_modify( ui_panelReset, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

// build funtions

void ui_settingsScreen3_screen_init(void)
{
ui_settingsScreen3 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_settingsScreen3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_settingsScreen3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_settingsScreen3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_btnAdvancedOptions = lv_button_create(ui_settingsScreen3);
lv_obj_set_width( ui_btnAdvancedOptions, 120);
lv_obj_set_height( ui_btnAdvancedOptions, 50);
lv_obj_set_x( ui_btnAdvancedOptions, 170 );
lv_obj_set_y( ui_btnAdvancedOptions, 20 );
lv_obj_set_align( ui_btnAdvancedOptions, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnAdvancedOptions, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_btnAdvancedOptions, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnAdvancedOptions, lv_color_hex(0x7B1008), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnAdvancedOptions, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_btnAdvancedOptions, lv_color_hex(0x293031), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_btnAdvancedOptions, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_btnAdvancedOptions, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_btnAdvancedOptions, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label36 = lv_label_create(ui_btnAdvancedOptions);
lv_obj_set_width( ui_Label36, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label36, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label36, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label36,"ADVANCED\nOPTIONS");

ui_btnControllerFirmware = lv_button_create(ui_settingsScreen3);
lv_obj_set_width( ui_btnControllerFirmware, 120);
lv_obj_set_height( ui_btnControllerFirmware, 50);
lv_obj_set_x( ui_btnControllerFirmware, 170 );
lv_obj_set_y( ui_btnControllerFirmware, -40 );
lv_obj_set_align( ui_btnControllerFirmware, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnControllerFirmware, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_btnControllerFirmware, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnControllerFirmware, lv_color_hex(0x7B1008), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnControllerFirmware, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_btnControllerFirmware, lv_color_hex(0x293031), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_btnControllerFirmware, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_btnControllerFirmware, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_btnControllerFirmware, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label28 = lv_label_create(ui_btnControllerFirmware);
lv_obj_set_width( ui_Label28, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label28, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label28, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label28,"CONTROLLER\nFIRMWARE");

ui_btnReset = lv_button_create(ui_settingsScreen3);
lv_obj_set_width( ui_btnReset, 120);
lv_obj_set_height( ui_btnReset, 50);
lv_obj_set_x( ui_btnReset, 170 );
lv_obj_set_y( ui_btnReset, 80 );
lv_obj_set_align( ui_btnReset, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnReset, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_btnReset, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnReset, lv_color_hex(0x7B1008), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnReset, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_btnReset, lv_color_hex(0x293031), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_btnReset, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_btnReset, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label11 = lv_label_create(ui_btnReset);
lv_obj_set_width( ui_Label11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label11, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label11,"RESET");

ui_Label32 = lv_label_create(ui_settingsScreen3);
lv_obj_set_width( ui_Label32, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label32, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label32, 50 );
lv_obj_set_y( ui_Label32, 120 );
lv_obj_set_align( ui_Label32, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label32,"Controller Ver:");

ui_Label10 = lv_label_create(ui_settingsScreen3);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label10, -190 );
lv_obj_set_y( ui_Label10, 120 );
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label10,"Screen Ver:");

ui_lblVersion = lv_label_create(ui_settingsScreen3);
lv_obj_set_width( ui_lblVersion, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblVersion, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblVersion, 170 );
lv_obj_set_y( ui_lblVersion, 120 );
lv_obj_set_align( ui_lblVersion, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblVersion,"Not Paired");

ui_lblVersion1 = lv_label_create(ui_settingsScreen3);
lv_obj_set_width( ui_lblVersion1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblVersion1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblVersion1, -80 );
lv_obj_set_y( ui_lblVersion1, 120 );
lv_obj_set_align( ui_lblVersion1, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblVersion1,"---");

ui_btnBack3 = lv_button_create(ui_settingsScreen3);
lv_obj_set_width( ui_btnBack3, 50);
lv_obj_set_height( ui_btnBack3, 50);
lv_obj_set_x( ui_btnBack3, -186 );
lv_obj_set_y( ui_btnBack3, -80 );
lv_obj_set_align( ui_btnBack3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnBack3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_btnBack3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnBack3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnBack3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( ui_btnBack3, &ui_img_valmar_back_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_image_recolor(ui_btnBack3, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_recolor_opa(ui_btnBack3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_btnBack3, lv_color_hex(0x293031), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_btnBack3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_btnBack3, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_btnPairing = lv_button_create(ui_settingsScreen3);
lv_obj_set_width( ui_btnPairing, 120);
lv_obj_set_height( ui_btnPairing, 50);
lv_obj_set_x( ui_btnPairing, 170 );
lv_obj_set_y( ui_btnPairing, -100 );
lv_obj_set_align( ui_btnPairing, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnPairing, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_btnPairing, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnPairing, lv_color_hex(0x7B1008), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnPairing, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_btnPairing, lv_color_hex(0x293031), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_btnPairing, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_btnPairing, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_btnPairing, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label24 = lv_label_create(ui_btnPairing);
lv_obj_set_width( ui_Label24, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label24, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label24, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label24,"PAIR\nCONTROLLER");

ui_Label29 = lv_label_create(ui_settingsScreen3);
lv_obj_set_width( ui_Label29, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label29, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label29, -20 );
lv_obj_set_y( ui_Label29, -10 );
lv_obj_set_align( ui_Label29, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label29,"Connect to a new rate controller  \n\n\n\nUpdate rate controller firmware   \n\n\n\n\n\n\n\n\nReset Screen and rate controller  ");
lv_obj_set_style_text_letter_space(ui_Label29, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Label29, -2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label29, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panelFirmware = lv_obj_create(ui_settingsScreen3);
lv_obj_set_width( ui_panelFirmware, 480);
lv_obj_set_height( ui_panelFirmware, 272);
lv_obj_set_align( ui_panelFirmware, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_panelFirmware, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_remove_flag( ui_panelFirmware, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_panelFirmware, lv_color_hex(0x78110A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_panelFirmware, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_panelFirmware, lv_color_hex(0x293031), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_panelFirmware, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_panelFirmware, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblFirmwareWarning = lv_label_create(ui_panelFirmware);
lv_obj_set_width( ui_lblFirmwareWarning, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblFirmwareWarning, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblFirmwareWarning, 5 );
lv_obj_set_y( ui_lblFirmwareWarning, 5 );
lv_obj_set_align( ui_lblFirmwareWarning, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblFirmwareWarning,"Do you wish to enter firmware update mode?");
lv_obj_set_style_text_align(ui_lblFirmwareWarning, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image6 = lv_image_create(ui_panelFirmware);
lv_image_set_src(ui_Image6, &ui_img_1608339404);
lv_obj_set_width( ui_Image6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image6, 0 );
lv_obj_set_y( ui_Image6, -80 );
lv_obj_set_align( ui_Image6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image6, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_Image6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_btnFirmwareCancel = lv_button_create(ui_panelFirmware);
lv_obj_set_width( ui_btnFirmwareCancel, 100);
lv_obj_set_height( ui_btnFirmwareCancel, 50);
lv_obj_set_x( ui_btnFirmwareCancel, 80 );
lv_obj_set_y( ui_btnFirmwareCancel, 80 );
lv_obj_set_align( ui_btnFirmwareCancel, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnFirmwareCancel, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_btnFirmwareCancel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnFirmwareCancel, lv_color_hex(0x293031), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnFirmwareCancel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblCancelButton = lv_label_create(ui_btnFirmwareCancel);
lv_obj_set_width( ui_lblCancelButton, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblCancelButton, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_lblCancelButton, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblCancelButton,"CANCEL");

ui_btnFirmwareUpdate = lv_button_create(ui_panelFirmware);
lv_obj_set_width( ui_btnFirmwareUpdate, 100);
lv_obj_set_height( ui_btnFirmwareUpdate, 50);
lv_obj_set_x( ui_btnFirmwareUpdate, -80 );
lv_obj_set_y( ui_btnFirmwareUpdate, 80 );
lv_obj_set_align( ui_btnFirmwareUpdate, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnFirmwareUpdate, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_btnFirmwareUpdate, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnFirmwareUpdate, lv_color_hex(0x293031), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnFirmwareUpdate, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label6 = lv_label_create(ui_btnFirmwareUpdate);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"UPDATE");

ui_panelReset = lv_obj_create(ui_settingsScreen3);
lv_obj_set_width( ui_panelReset, 480);
lv_obj_set_height( ui_panelReset, 272);
lv_obj_set_align( ui_panelReset, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_panelReset, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_remove_flag( ui_panelReset, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_panelReset, lv_color_hex(0x78110A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_panelReset, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_panelReset, lv_color_hex(0x293031), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_panelReset, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_panelReset, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label12 = lv_label_create(ui_panelReset);
lv_obj_set_width( ui_Label12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label12, 0 );
lv_obj_set_y( ui_Label12, 3 );
lv_obj_set_align( ui_Label12, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label12,"Are you sure you want to reset to defaults?\n\nThis will erase all saved settings including calibration\nand pairing on both screen and controller.\nThis can not be undone.");
lv_obj_set_style_text_align(ui_Label12, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image5 = lv_image_create(ui_panelReset);
lv_image_set_src(ui_Image5, &ui_img_1608339404);
lv_obj_set_width( ui_Image5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image5, 0 );
lv_obj_set_y( ui_Image5, -75 );
lv_obj_set_align( ui_Image5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image5, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_Image5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_btnResetYes = lv_button_create(ui_panelReset);
lv_obj_set_width( ui_btnResetYes, 100);
lv_obj_set_height( ui_btnResetYes, 50);
lv_obj_set_x( ui_btnResetYes, 75 );
lv_obj_set_y( ui_btnResetYes, 75 );
lv_obj_set_align( ui_btnResetYes, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnResetYes, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_btnResetYes, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnResetYes, lv_color_hex(0x293031), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnResetYes, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label13 = lv_label_create(ui_btnResetYes);
lv_obj_set_width( ui_Label13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label13, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label13,"YES");

ui_btnResetNo = lv_button_create(ui_panelReset);
lv_obj_set_width( ui_btnResetNo, 100);
lv_obj_set_height( ui_btnResetNo, 50);
lv_obj_set_x( ui_btnResetNo, -75 );
lv_obj_set_y( ui_btnResetNo, 75 );
lv_obj_set_align( ui_btnResetNo, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnResetNo, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_btnResetNo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnResetNo, lv_color_hex(0x293031), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnResetNo, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_btnResetNo);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"NO");

lv_obj_add_event_cb(ui_btnAdvancedOptions, ui_event_btnAdvancedOptions, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnControllerFirmware, ui_event_btnControllerFirmware, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnReset, ui_event_btnReset, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnBack3, ui_event_btnBack3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnPairing, ui_event_btnPairing, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnFirmwareCancel, ui_event_btnFirmwareCancel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnFirmwareUpdate, ui_event_btnFirmwareUpdate, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnResetYes, ui_event_btnResetYes, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnResetNo, ui_event_btnResetNo, LV_EVENT_ALL, NULL);
uic_settingsScreen3 = ui_settingsScreen3;
uic_btnAdvancedOptions = ui_btnAdvancedOptions;
uic_btnControllerFirmware = ui_btnControllerFirmware;
uic_btnReset = ui_btnReset;
uic_lblVersion = ui_lblVersion;
uic_btnPairing = ui_btnPairing;
uic_panelFirmware = ui_panelFirmware;
uic_lblFirmwareWarning = ui_lblFirmwareWarning;
uic_btnFirmwareCancel = ui_btnFirmwareCancel;
uic_lblCancelButton = ui_lblCancelButton;
uic_btnFirmwareUpdate = ui_btnFirmwareUpdate;
uic_panelReset = ui_panelReset;
uic_btnResetYes = ui_btnResetYes;
uic_btnResetNo = ui_btnResetNo;

}

void ui_settingsScreen3_screen_destroy(void)
{
   if (ui_settingsScreen3) lv_obj_del(ui_settingsScreen3);

// NULL screen variables
uic_settingsScreen3= NULL;
ui_settingsScreen3= NULL;
uic_btnAdvancedOptions= NULL;
ui_btnAdvancedOptions= NULL;
ui_Label36= NULL;
uic_btnControllerFirmware= NULL;
ui_btnControllerFirmware= NULL;
ui_Label28= NULL;
uic_btnReset= NULL;
ui_btnReset= NULL;
ui_Label11= NULL;
ui_Label32= NULL;
ui_Label10= NULL;
uic_lblVersion= NULL;
ui_lblVersion= NULL;
ui_lblVersion1= NULL;
ui_btnBack3= NULL;
uic_btnPairing= NULL;
ui_btnPairing= NULL;
ui_Label24= NULL;
ui_Label29= NULL;
uic_panelFirmware= NULL;
ui_panelFirmware= NULL;
uic_lblFirmwareWarning= NULL;
ui_lblFirmwareWarning= NULL;
ui_Image6= NULL;
uic_btnFirmwareCancel= NULL;
ui_btnFirmwareCancel= NULL;
uic_lblCancelButton= NULL;
ui_lblCancelButton= NULL;
uic_btnFirmwareUpdate= NULL;
ui_btnFirmwareUpdate= NULL;
ui_Label6= NULL;
uic_panelReset= NULL;
ui_panelReset= NULL;
ui_Label12= NULL;
ui_Image5= NULL;
uic_btnResetYes= NULL;
ui_btnResetYes= NULL;
ui_Label13= NULL;
uic_btnResetNo= NULL;
ui_btnResetNo= NULL;
ui_Label2= NULL;

}
