// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: Valmar_Screen

#include "ui.h"

lv_obj_t *uic_arcBacklight;
lv_obj_t *uic_settingsScreen;
lv_obj_t *ui_settingsScreen = NULL;lv_obj_t *ui_btnCalibrate3 = NULL;lv_obj_t *ui_arcBacklight = NULL;
// event funtions
void ui_event_btnCalibrate3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_screen_change( &ui_runScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_runScreen_screen_init);
}
}

void ui_event_arcBacklight( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      backlightControl( e );
}
}

// build funtions

void ui_settingsScreen_screen_init(void)
{
ui_settingsScreen = lv_obj_create(NULL);
lv_obj_remove_flag( ui_settingsScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_settingsScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_settingsScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_btnCalibrate3 = lv_button_create(ui_settingsScreen);
lv_obj_set_width( ui_btnCalibrate3, 50);
lv_obj_set_height( ui_btnCalibrate3, 50);
lv_obj_set_x( ui_btnCalibrate3, -186 );
lv_obj_set_y( ui_btnCalibrate3, -80 );
lv_obj_set_align( ui_btnCalibrate3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnCalibrate3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_btnCalibrate3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnCalibrate3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnCalibrate3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( ui_btnCalibrate3, &ui_img_valmar_back_png, LV_PART_MAIN | LV_STATE_DEFAULT );
ui_object_set_themeable_style_property(ui_btnCalibrate3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_IMAGE_RECOLOR, _ui_theme_color_valmarRed);
ui_object_set_themeable_style_property(ui_btnCalibrate3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_IMAGE_RECOLOR_OPA, _ui_theme_alpha_valmarRed);
ui_object_set_themeable_style_property(ui_btnCalibrate3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_spinboxOuline);
ui_object_set_themeable_style_property(ui_btnCalibrate3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_spinboxOuline);
lv_obj_set_style_border_width(ui_btnCalibrate3, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_arcBacklight = lv_arc_create(ui_settingsScreen);
lv_obj_set_width( ui_arcBacklight, 150);
lv_obj_set_height( ui_arcBacklight, 150);
lv_obj_set_x( ui_arcBacklight, 0 );
lv_obj_set_y( ui_arcBacklight, 42 );
lv_obj_set_align( ui_arcBacklight, LV_ALIGN_CENTER );
lv_arc_set_range(ui_arcBacklight, 10,255);
lv_arc_set_value(ui_arcBacklight, 200);

lv_obj_add_event_cb(ui_btnCalibrate3, ui_event_btnCalibrate3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_arcBacklight, ui_event_arcBacklight, LV_EVENT_ALL, NULL);
uic_settingsScreen = ui_settingsScreen;
uic_arcBacklight = ui_arcBacklight;

}

void ui_settingsScreen_screen_destroy(void)
{
   if (ui_settingsScreen) lv_obj_del(ui_settingsScreen);

// NULL screen variables
uic_settingsScreen= NULL;
ui_settingsScreen= NULL;
ui_btnCalibrate3= NULL;
uic_arcBacklight= NULL;
ui_arcBacklight= NULL;

}
