// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: Valmar_Screen

#include "ui.h"

const ui_theme_variable_t _ui_theme_color_ValmarRed[1] = {0x7B1008};
const ui_theme_variable_t _ui_theme_alpha_ValmarRed[1] = {255};

const ui_theme_variable_t _ui_theme_color_ValmarGrey[1] = {0x393839};
const ui_theme_variable_t _ui_theme_alpha_ValmarGrey[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;

void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

